# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "dcrgitwwpnudhbuunnst"

[api]
enabled = true

[db]
major_version = 17
