import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { loadSystemPrompt } from "../lib/prompt-loader";

const FIXTURE_DIR = "agent/script-agent/fixtures";
const REPORT_PATH = "agent/script-agent/PROMPT_FIXTURE_REPORT.md";

type PromptFixture = {
  id: string;
  label: string;
  directionId: string;
  additionalSharedPromptFiles?: string[];
  requiredTerms?: string[];
  forbiddenTerms?: string[];
  requiredMarkers?: string[];
  forbiddenMarkers?: string[];
};

type FixtureResult = {
  id: string;
  label: string;
  directionId: string;
  hash: string;
  length: number;
  additionalSharedPromptFiles: string[];
};

function fail(message: string): never {
  throw new Error(`script-agent prompt fixtures failed: ${message}`);
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function readFixtures(): PromptFixture[] {
  const files = fs.readdirSync(FIXTURE_DIR).filter((file) => file.endsWith(".json")).sort();
  if (files.length === 0) fail("no fixtures found");
  return files.map((file) => {
    const fixture = JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, file), "utf8")) as PromptFixture;
    if (!fixture.id || !fixture.directionId) fail(`invalid fixture: ${file}`);
    return fixture;
  });
}

const results: FixtureResult[] = [];
for (const fixture of readFixtures()) {
  const prompt = loadSystemPrompt(fixture.directionId, {
    assemblyMode: "modular",
    additionalSharedPromptFiles: fixture.additionalSharedPromptFiles,
  });
  for (const term of fixture.requiredTerms ?? []) {
    if (!prompt.includes(term)) fail(`${fixture.id}: missing required term ${term}`);
  }
  for (const term of fixture.forbiddenTerms ?? []) {
    if (prompt.includes(term)) fail(`${fixture.id}: forbidden term present ${term}`);
  }
  for (const marker of fixture.requiredMarkers ?? []) {
    if (!prompt.includes(marker)) fail(`${fixture.id}: missing required marker ${marker}`);
  }
  for (const marker of fixture.forbiddenMarkers ?? []) {
    if (prompt.includes(marker)) fail(`${fixture.id}: forbidden marker present ${marker}`);
  }
  results.push({
    id: fixture.id,
    label: fixture.label,
    directionId: fixture.directionId,
    hash: sha256(prompt),
    length: prompt.length,
    additionalSharedPromptFiles: fixture.additionalSharedPromptFiles ?? [],
  });
}

const report = `# Prompt Fixture Report

Generated by \`npm run smoke:prompt-fixtures\`. This report is deterministic and intentionally has no timestamp.

| Fixture | Direction | Extra shared files | Hash | Length |
| --- | --- | --- | --- | --- |
${results
  .map(
    (result) =>
      `| ${result.label} | \`${result.directionId}\` | ${
        result.additionalSharedPromptFiles.length
          ? result.additionalSharedPromptFiles.map((file) => `\`${file}\``).join("<br>")
          : "none"
      } | \`${result.hash}\` | ${result.length} |`
  )
  .join("\n")}
`;

fs.writeFileSync(REPORT_PATH, report, "utf8");

console.log(
  JSON.stringify(
    {
      ok: true,
      reportPath: REPORT_PATH,
      fixtures: results,
    },
    null,
    2
  )
);
